# -*- coding: utf-8 -*-
"""wordcloud.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V12hXfA84QhdekzECJv678jQudMhWIFq
"""

# excersize 1
# auther Luuk Marcus
# state ongoing

#Excersize 2
# author: Elsa
# state: ongoing

